[package]
name = "muon"
version = "0.1.2"
authors = ["Kent D <kent.daleng@nav.no>"]
edition = "2018"

[profile.dev.package.'*']
opt-level = 3

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.3"
