on: 
  push:
      branches:
      - 'master'
      paths:
      - build/**
      - .github/workflows/publish.yml
jobs:
    deploy:
        name: Deploy new version of game
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Publish changes
          uses: appleboy/scp-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USER }}
            passphrase: ${{ secrets.PASSPHRASE }}
            key: ${{ secrets.KEY }}
            source: "build/muon.wasm"
            target: "muon"
            strip_components: 1
